### ISSUE TITLE
GTK3 version crashes when removing text from search field

### ISSUE THREAD

**Issue by pizzadude** [ahodesuka/ahoviewer#105]
The GTK3 version of ahoviewer crashes immediately after typing something into the search field, and then deleting the search term by pressing backspace a few times. This is on Fedora 32 KDE.

Terminal output:
```
/usr/bin/ahoviewer 
Gtk-Message: 10:58:37.613: Failed to load module "appmenu-gtk-module"
Using videosink of type 'xvimagesink'

(ahoviewer:1840669): Gtk-WARNING **: 10:58:37.899: Attempting to read the recently used resources file at '/home/user/.local/share/recently-used.xbel', but the parser failed: Error reading file “/home/user/.local/share/recently-used.xbel”: Is a directory.
/builddir/build/BUILD/gcc-10.2.1-20200723/obj-x86_64-redhat-linux/x86_64-redhat-linux/libstdc++-v3/include/bits/basic_string.h:1116: std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::reference std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::back() [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>; std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::reference = char&]: Assertion '!empty()' failed.
Aborted (core dumped)
```

So for now I have to use the gtk2 branch.

**Comment by ahodesuka** [comment]
I can't reproduce this when compiling with gcc-9.3.0 or clang-10.0.0, and can't really see what's going on without a full backtrace.

**Comment by ahodesuka** [comment]
Installed gcc-10.2.1 and still can't reproduce this.

**Comment by pizzadude** [comment]
Here's a backtrace.
```
gdb -ex run --args ./src/ahoviewer
GNU gdb (GDB) Fedora 9.1-6.fc32
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./src/ahoviewer...
Starting program: /home/user/src/ahoviewer/build/src/ahoviewer 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
[New Thread 0x7fffe76a3700 (LWP 2334078)]
[New Thread 0x7fffe6ea2700 (LWP 2334079)]
[New Thread 0x7fffe669f700 (LWP 2334080)]
Gtk-Message: 08:23:08.813: Failed to load module "appmenu-gtk-module"
[New Thread 0x7fffe5b5b700 (LWP 2334081)]
[New Thread 0x7fffe535a700 (LWP 2334082)]
[New Thread 0x7fffcffff700 (LWP 2334083)]
Using videosink of type 'xvimagesink'
[New Thread 0x7fffcf7fe700 (LWP 2334084)]
[New Thread 0x7fffceffd700 (LWP 2334085)]
[New Thread 0x7fffce7fc700 (LWP 2334086)]
[New Thread 0x7fffcdffb700 (LWP 2334087)]
[Thread 0x7fffcdffb700 (LWP 2334087) exited]
[Thread 0x7fffce7fc700 (LWP 2334086) exited]
[New Thread 0x7fffce7fc700 (LWP 2334088)]
[New Thread 0x7fffcdffb700 (LWP 2334089)]
[New Thread 0x7fffccef0700 (LWP 2334090)]
[New Thread 0x7fffb7fff700 (LWP 2334091)]

(ahoviewer:2334050): Gtk-WARNING **: 08:23:09.640: Attempting to read the recently used resources file at '/home/user/.local/share/recently-used.xbel', but the parser failed: Error reading file “/home/user/.local/share/recently-used.xbel”: Is a directory.
[Thread 0x7fffe535a700 (LWP 2334082) exited]
[Thread 0x7fffe5b5b700 (LWP 2334081) exited]
[Thread 0x7fffcf7fe700 (LWP 2334084) exited]
/builddir/build/BUILD/gcc-10.2.1-20200723/obj-x86_64-redhat-linux/x86_64-redhat-linux/libstdc++-v3/include/bits/basic_string.h:1116: std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::reference std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::back() [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>; std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::reference = char&]: Assertion '!empty()' failed.
Missing separate debuginfos, use: dnf debuginfo-install GConf2-3.2.6-27.fc31.x86_64 at-spi2-atk-2.34.2-1.fc32.x86_64 at-spi2-core-2.36.0-1.fc32.x86_64 atk-2.36.0-1.fc32.x86_64 atkmm-2.24.3-4.fc32.x86_64 bzip2-libs-1.0.8-2.fc32.x86_64 cairo-1.16.0-8.fc32.x86_64 cairo-gobject-1.16.0-8.fc32.x86_64 cairomm-1.12.0-12.fc32.x86_64 cyrus-sasl-lib-2.1.27-4.fc32.x86_64 dbus-glib-0.110-7.fc32.x86_64 dbus-libs-1.12.20-1.fc32.x86_64 expat-2.2.8-2.fc32.x86_64 fontconfig-2.13.92-9.fc32.x86_64 freetype-2.10.2-1.fc32.x86_64 fribidi-1.0.9-1.fc32.x86_64 gdk-pixbuf2-2.40.0-2.fc32.x86_64 glib2-2.64.5-1.fc32.x86_64 glibc-2.31-4.fc32.x86_64 glibmm24-2.64.2-1.fc32.x86_64 graphite2-1.3.14-1.fc32.x86_64 gstreamer1-1.16.2-2.fc32.x86_64 gstreamer1-plugins-base-1.16.2-3.fc32.x86_64 gtk3-3.24.22-1.fc32.x86_64 gtkmm30-3.24.2-2.fc32.x86_64 gvfs-client-1.44.1-1.fc32.x86_64 harfbuzz-2.6.4-3.fc32.x86_64 kde-gtk-config-5.19.5-1.fc32.x86_64 krb5-libs-1.18.2-20.fc32.x86_64 libX11-1.6.12-1.fc32.x86_64 libXau-1.0.9-3.fc32.x86_64 libXcomposite-0.4.5-2.fc32.x86_64 libXcursor-1.2.0-2.fc32.x86_64 libXdamage-1.1.5-2.fc32.x86_64 libXext-1.3.4-3.fc32.x86_64 libXfixes-5.0.3-11.fc32.x86_64 libXi-1.7.10-3.fc32.x86_64 libXinerama-1.1.4-5.fc32.x86_64 libXrender-0.9.10-11.fc32.x86_64 libXv-1.0.11-11.fc32.x86_64 libbrotli-1.0.7-10.fc32.x86_64 libconfig-1.7.2-5.fc32.x86_64 libcurl-7.69.1-5.fc32.x86_64 libdatrie-0.2.9-11.fc32.x86_64 libepoxy-1.5.4-2.fc32.x86_64 libffi-3.1-24.fc32.x86_64 libgcc-10.2.1-1.fc32.x86_64 libgcrypt-1.8.5-3.fc32.x86_64 libgpg-error-1.36-3.fc32.x86_64 libidn2-2.3.0-2.fc32.x86_64 libnghttp2-1.41.0-1.fc32.x86_64 libpng-1.6.37-3.fc32.x86_64 libpsl-0.21.0-4.fc32.x86_64 librsvg2-2.48.8-1.fc32.x86_64 libsecret-0.20.3-1.fc32.x86_64 libsigc++20-2.10.3-1.fc32.x86_64 libthai-0.1.28-4.fc32.x86_64 libwayland-cursor-1.18.0-1.fc32.x86_64 libwayland-egl-1.18.0-1.fc32.x86_64 libxcb-1.13.1-4.fc32.x86_64 libxkbcommon-0.10.0-2.fc32.x86_64 libxml2-2.9.10-3.fc32.x86_64 libzip-1.6.1-1.fc32.x86_64 nss-mdns-0.14.1-9.fc32.x86_64 openssl-libs-1.1.1g-1.fc32.x86_64 orc-0.4.31-2.fc32.x86_64 pango-1.44.7-2.fc32.x86_64 pangomm-2.42.1-1.fc32.x86_64 pcre-8.44-1.fc32.x86_64 pcre2-10.35-4.fc32.x86_64 unity-gtk3-module-0.0.0+17.04.20170403-9.fc32.x86_64
--Type <RET> for more, q to quit, c to continue without paging--bt

Thread 1 "ahoviewer" received signal SIGABRT, Aborted.
0x00007ffff5e369e5 in raise () from /lib64/libc.so.6
(gdb) bt
#0  0x00007ffff5e369e5 in raise () at /lib64/libc.so.6
#1  0x00007ffff5e1f895 in abort () at /lib64/libc.so.6
#2  0x00007ffff620ed98 in  () at /lib64/libstdc++.so.6
#3  0x00007ffff6290566 in  () at /lib64/libstdc++.so.6
#4  0x00000000004db103 in AhoViewer::Booru::TagEntry::on_text_changed() (this=0x1a55c30) at ../src/booru/tagentry.cc:48
#5  0x00000000004de7c0 in sigc::bound_mem_functor0<void, AhoViewer::Booru::TagEntry>::operator()() const (this=0x1a27f68)
    at /usr/include/sigc++-2.0/sigc++/functors/mem_fun.h:1991
#6  0x00000000004de444 in sigc::adaptor_functor<sigc::bound_mem_functor0<void, AhoViewer::Booru::TagEntry> >::operator()() const (this=0x1a27f60) at /usr/include/sigc++-2.0/sigc++/adaptors/adaptor_trait.h:256
#7  0x00000000004ddef7 in sigc::internal::slot_call0<sigc::bound_mem_functor0<void, AhoViewer::Booru::TagEntry>, void>::call_it(sigc::internal::slot_rep*) (rep=0x1a27f30) at /usr/include/sigc++-2.0/sigc++/functors/slot.h:136
#8  0x00007ffff7f4b4cc in Glib::SignalProxyNormal::slot0_void_callback(_GObject*, void*) () at /lib64/libglibmm-2.4.so.1
#9  0x00007ffff7e9788a in g_closure_invoke () at /lib64/libgobject-2.0.so.0
#10 0x00007ffff7eaa612 in signal_emit_unlocked_R.isra.0 () at /lib64/libgobject-2.0.so.0
#11 0x00007ffff7eb0af9 in g_signal_emit_valist () at /lib64/libgobject-2.0.so.0
#12 0x00007ffff7eb0e8f in g_signal_emit_by_name () at /lib64/libgobject-2.0.so.0
#13 0x00007ffff6e769e9 in end_change () at /lib64/libgtk-3.so.0
#14 0x00007ffff7ad9f11 in Gtk::Editable_Class::delete_text_callback(_GtkEditable*, int, int) () at /lib64/libgtkmm-3.0.so.1
#15 0x00007ffff7e9788a in g_closure_invoke () at /lib64/libgobject-2.0.so.0
#16 0x00007ffff7ea9e7e in signal_emit_unlocked_R.isra.0 () at /lib64/libgobject-2.0.so.0
#17 0x00007ffff7eb0af9 in g_signal_emit_valist () at /lib64/libgobject-2.0.so.0
#18 0x00007ffff7eb0e8f in g_signal_emit_by_name () at /lib64/libgobject-2.0.so.0
#19 0x00007ffff6e76a2e in gtk_entry_delete_text () at /lib64/libgtk-3.so.0
#20 0x00007ffff7ad9a21 in Gtk::Editable_Class::do_delete_text_vfunc_callback(_GtkEditable*, int, int) ()
    at /lib64/libgtkmm-3.0.so.1
#21 0x00007ffff6e7e8f5 in gtk_entry_backspace () at /lib64/libgtk-3.so.0
#22 0x00007ffff7e9788a in g_closure_invoke () at /lib64/libgobject-2.0.so.0
#23 0x00007ffff7ea9e7e in signal_emit_unlocked_R.isra.0 () at /lib64/libgobject-2.0.so.0
#24 0x00007ffff6de548f in gtk_binding_entry_activate () at /lib64/libgtk-3.so.0
#25 0x00007ffff6de5948 in binding_activate () at /lib64/libgtk-3.so.0
#26 0x00007ffff6de5af1 in gtk_bindings_activate_list () at /lib64/libgtk-3.so.0
#27 0x00007ffff6de6f96 in gtk_bindings_activate_event () at /lib64/libgtk-3.so.0
#28 0x00007ffff6e7b9f7 in gtk_entry_key_press () at /lib64/libgtk-3.so.0
#29 0x00007ffff7b80099 in Gtk::Widget::on_key_press_event(_GdkEventKey*) () at /lib64/libgtkmm-3.0.so.1
```
For now I will try to build with clang.

**Comment by pizzadude** [comment]
I get the same error even if I build with clang.

**Comment by ahodesuka** [comment]
Is the crash occurring when the tag entry is empty (after deleting all the text in it)?
Or is it just randomly when hitting backspace?

**Comment by ahodesuka** [comment]
Check if 518c20c (master) fixes this

**Comment by pizzadude** [comment]
@ahodesuka Thanks, that fixes it.
