### ISSUE TITLE
Failure to load plugin.

### ISSUE THREAD

**Issue by colinMcGrail** [ahodesuka/ahoviewer#145]
The program outputs the following error on startup:

`Error importing plugin 'sankakucomplex':
Traceback (most recent call last): 
File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/colin/.local/share/ahoviewer/plugins/sankakucomplex/sankakucomplex.py", line 4, in <module>
    gi.require_version('Ahoviewer', '1.0')
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 126, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Ahoviewer not available`

**Comment by ahodesuka** [comment]
This is caused by the `Ahoviewer-1.0.typelib` file not being found.
The .typelib file should be installed into `/usr/local/lib/girepository-1.0` when running `meson install`
