### ISSUE TITLE
Freeze after loading more than ~1000 images

### ISSUE THREAD

**Issue by OrdinaryMagician** [ahodesuka/ahoviewer#34]
The number is in no way exact.

I often hit a point while browsing where all thumbnails fall back to the "image missing" icon, and after a while the entire program freezes.

I'm currently trying to get a bit more info out of this.

**Comment by OrdinaryMagician** [comment]
OK, once I hit that point, I start seeing messages like these on stderr:
```
(ahoviewer:15397): glibmm-CRITICAL **: 
unhandled exception (type Glib::Error) in signal handler:
domain: g-file-error-quark
code  : 14
what  : Failed to open file '/tmp/ahoviewer.5KZGEY/Gelbooru/thumbnails/thumbnail_1bb85bd37c650561d3128bcaab31d093.jpg': Too many open files
```

I also see various ```Error while downloading thumbnail [...] Couldn't resolve host name``` messages, too, which could be why the thumbs become missing icons.

Interrupting and getting a trace shows me that it's stuck in a pthread_join() call
```
#0  0x00007ffff0bb268d in pthread_join () from /usr/lib/libpthread.so.0
#1  0x00007ffff474e687 in ?? () from /usr/lib/libglib-2.0.so.0
#2  0x00007ffff4730bba in g_thread_join () from /usr/lib/libglib-2.0.so.0
#3  0x000000000042e2be in AhoViewer::Booru::ImageList::load (this=0x1397540, 
    posts=..., page=...) at booru/imagelist.cc:57
#4  0x0000000000430dd8 in AhoViewer::Booru::Page::on_posts_downloaded (
    this=0x137dc30) at booru/page.cc:340
#5  0x00007ffff64c05ba in Glib::DispatchNotifier::pipe_io_handler(Glib::IOCondition) () from /usr/lib/libglibmm-2.4.so.1
#6  0x00007ffff64c2ff7 in Glib::IOSource::dispatch(sigc::slot_base*) ()
   from /usr/lib/libglibmm-2.4.so.1
#7  0x00007ffff64c29ef in Glib::Source::dispatch_vfunc(_GSource*, int (*)(void*), void*) () from /usr/lib/libglibmm-2.4.so.1
#8  0x00007ffff4709c3a in g_main_context_dispatch ()
   from /usr/lib/libglib-2.0.so.0
#9  0x00007ffff4709fe0 in ?? () from /usr/lib/libglib-2.0.so.0
#10 0x00007ffff470a302 in g_main_loop_run () from /usr/lib/libglib-2.0.so.0
#11 0x00007ffff70474e7 in gtk_main () from /usr/lib/libgtk-x11-2.0.so.0
#12 0x00007ffff7a3e16f in Gtk::Main::run(Gtk::Window&) ()
   from /usr/lib/libgtkmm-2.4.so.1
#13 0x000000000041c803 in main (argc=1, argv=0x7fffffffdeb8) at main.cc:51
```

**Comment by ahodesuka** [comment]
I'll try taking a look into this.

**Comment by OrdinaryMagician** [comment]
It's pretty much just from having too many file handles at the same time. Makes sense considering all thumbnails are saved to a temporary folder.

A workaround is to raise the max file descriptors in limits.conf.
