### ISSUE TITLE
SIGSEGV on Linux when a download fails

### ISSUE THREAD

**Issue by oliwer** [ahodesuka/ahoviewer#82]
I was running the booru browser with gdb when this happened.

```
Error while downloading thumbnail https://gelbooru.com/thumbnails/ba/3e/thumbnail_ba3e4cb8da74d95224c130242fb3f323.jpg
  Failure when receiving data from the peer
[New Thread 0x7ffe13fff700 (LWP 23006)]
[Thread 0x7ffe13fff700 (LWP 23006) exited]

Thread 672 "ahoviewer" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffe0fffe700 (LWP 23004)]
0x00007ffff6e42a39 in ?? () from /usr/lib/x86_64-linux-gnu/libcurl.so.4
#0  0x00007ffff6e42a39 in ?? () from /usr/lib/x86_64-linux-gnu/libcurl.so.4
#1  0x00007ffff6e42df5 in curl_multi_socket_action () from /usr/lib/x86_64-linux-gnu/libcurl.so.4
#2  0x00005555555a2963 in AhoViewer::Booru::ImageFetcher::event_cb (this=0x7fff480a8d50, sockfd=<optimized out>, cond=<optimized out>) at booru/imagefetcher.cc:147
#3  0x00007ffff747c7ef in ?? () from /usr/lib/x86_64-linux-gnu/libglibmm-2.4.so.1
#4  0x00007ffff70fe958 in g_main_context_dispatch () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#5  0x00007ffff70fed48 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#6  0x00007ffff70ff042 in g_main_loop_run () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#7  0x00005555555a317b in AhoViewer::Booru::ImageFetcher::<lambda()>::operator() (__closure=0x555559ca75f8) at booru/imagefetcher.cc:72
#8  std::__invoke_impl<void, AhoViewer::Booru::ImageFetcher::ImageFetcher(int)::<lambda()> > (__f=...) at /usr/include/c++/7/bits/invoke.h:60
#9  std::__invoke<AhoViewer::Booru::ImageFetcher::ImageFetcher(int)::<lambda()> > (__fn=...) at /usr/include/c++/7/bits/invoke.h:95
#10 std::thread::_Invoker<std::tuple<AhoViewer::Booru::ImageFetcher::ImageFetcher(int)::<lambda()> > >::_M_invoke<0> (this=0x555559ca75f8) at /usr/include/c++/7/thread:234
#11 std::thread::_Invoker<std::tuple<AhoViewer::Booru::ImageFetcher::ImageFetcher(int)::<lambda()> > >::operator() (this=0x555559ca75f8) at /usr/include/c++/7/thread:243
#12 std::thread::_State_impl<std::thread::_Invoker<std::tuple<AhoViewer::Booru::ImageFetcher::ImageFetcher(int)::<lambda()> > > >::_M_run(void) (this=0x555559ca75f0) at /usr/include/c++/7/thread:186
#13 0x00007ffff68de420 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#14 0x00007ffff668c182 in start_thread (arg=<optimized out>) at pthread_create.c:486
#15 0x00007ffff65b5b1f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
A debugging session is active.

	Inferior 1 [process 21611] will be killed.

```

**Comment by oliwer** [comment]
Nevermind. I was still running v1.5.0 so this might already be fixed.
